services:
  - type: web
    name: partyon-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_ORIGIN
        sync: false
